export const teamCopy = {
  title: 'Team',
  subtitle: 'Content managers och deras kundpuls',
  addCm: 'Lägg till',
  sortAnomalous: 'Avvikande aktivitet först',
  sortStandard: 'Standardordning',
  payroll: 'Payroll',
  setAbsence: 'Sätt frånvaro',
  edit: 'Redigera',
  endAbsence: 'Avsluta frånvaro',
  loading: 'Laddar team...',
  emptyTitle: 'Inga content managers ännu',
  emptyHint: 'Lägg till din första CM för att börja koppla kunder.',
  activeAbsenceUntil: (date: string) => `Frånvarande till ${date}`,
  activeAbsenceRange: (startsOn: string, endsOn: string) =>
    `Aktiv frånvaro ${startsOn} - ${endsOn}`,
  deviation: (pct: number) => `Avvikelse ${pct}%`,
  customers: 'Kunder',
  mrr: 'MRR',
  followers: 'Följare',
  flow: 'Flöde',
  noLocation: 'Ingen ort angiven',
  noCustomers: 'Inga kunder kopplade än.',
  customerTableVirtualized: (count: number) =>
    `Virtualiserad kundlista aktiv för ${count} kunder.`,
  activitySummary: (active: number, total: number, median: number, longest: number) =>
    `${active}/${total} aktiva dagar · median ${median} · längsta vila ${longest}d`,
  basedOnMrr: 'Baserat på total MRR för servade kunder',
  totalMrr: 'Total MRR',
  compensationPreview: (pct: number) => `~${pct}% ersättning`,
  cover: 'Cover',
  history: 'Historik och handovers',
  historyCurrent: 'nu',
  scheduledChange: (date: string) => `schemalagt byte ${date}`,
  standardAssignment: 'Ordinarie CM',
  replacementAssigned: 'Ersättare kopplad',
  payrollPrimary: 'Ordinarie CM',
  payrollBackup: 'Ersättare',
  customerColumn: 'Kund',
  typeLabel: 'Typ',
  payrollLabel: 'Payroll',
  days: 'dagar',
} as const;

export const cmEditCopy = {
  title: 'Redigera CM',
  description: 'Uppdatera profil, kommission och kundansvar.',
  replaceAvatar: 'Byt',
  replaceAvatarHint: 'Ladda upp en ny bild eller ange en URL manuellt.',
  uploadAvatar: 'Ladda upp bild',
  uploadingAvatar: 'Laddar upp bild...',
  avatarUploadFailed: 'Kunde inte ladda upp profilbilden',
  avatarUrlToggle: 'Använd bild-URL i stället',
  avatarUrlToggleHide: 'Dölj URL-fält',
  name: 'Namn',
  email: 'E-post',
  phone: 'Telefon',
  city: 'Ort',
  bio: 'Bio',
  avatarUrl: 'Profilbild (URL)',
  commissionRate: 'Kommission (%)',
  reassignAll: 'Omfördela alla kunder',
  selectCm: 'Välj CM...',
  moveCustomers: (count: number) => `Flytta ${count} kunder`,
  movingCustomers: (count: number) => `Flyttar ${count} kunder...`,
  movingProgress: (current: number, total: number) => `Flyttar ${current}/${total} kunder...`,
  save: 'Spara',
  saving: 'Sparar...',
  cancel: 'Avbryt',
  archive: 'Arkivera CM',
  archiveTitle: 'Arkivera CM?',
  archiveDescriptionWithCustomers: (count: number) =>
    `CM:n markeras som inaktiv. Omfördela först ${count} kunder innan arkivering.`,
  archiveDescriptionWithoutCustomers:
    'CM:n markeras som inaktiv och tas bort från aktiv planering.',
  saveFailed: 'Misslyckades',
  profileSaved: 'Profilen uppdaterades.',
  reassignFailed: 'Kunde inte omfördela kunder',
  archiveBlocked:
    'CM:n har fortfarande aktiva kundansvar. Omfördela kunderna först.',
  archiveBlockedAction: 'Omfördela alla kunder',
  nameHint: 'Minst 2 tecken.',
  bioHint: 'Max 500 tecken.',
  avatarUrlHint: 'Valfritt. Ange full URL till profilbild.',
} as const;

export const cmAbsenceCopy = {
  title: 'Sätt frånvaro',
  description: (name: string) =>
    `Registrera frånvaro, datumintervall och eventuell ersättare för ${name}.`,
  type: 'Typ',
  startsOn: 'Startdatum',
  endsOn: 'Slutdatum',
  backupCm: 'Ersättare',
  noBackupCm: 'Ingen ersättare',
  compensation: 'Provision under frånvaro',
  replacementEarns: 'Ersättare får payout',
  replacementEarnsDescription: 'Operativt ansvar och payroll ligger på ersättaren.',
  primaryEarns: 'Ordinarie CM behåller payout',
  primaryEarnsDescription:
    'Puls suppressas men payroll ligger kvar på ordinarie CM.',
  note: 'Notering',
  payrollImpactTitle: 'Påverkan på payroll',
  payrollImpactPrimaryRetained: 'Ordinarie CM får payout under frånvaron',
  payrollImpactPrimarySuppressed: 'Ordinarie CM suppressas under frånvaron',
  payrollImpactBackupRetained: 'Ersättaren får payout under frånvaron',
  payrollImpactBackupSuppressed: 'Ingen ersättarpayout under frånvaron',
  backupRequired: 'Välj en ersättare för att tilldela payout',
  invalidRange: 'Slutdatum kan inte vara före startdatum',
  save: 'Spara frånvaro',
  saving: 'Sparar...',
  cancel: 'Avbryt',
  savedTitle: 'Frånvaro sparad',
  saveFailed: 'Kunde inte skapa frånvaro',
  typeLabels: {
    vacation: 'Semester',
    sick: 'Sjuk',
    parental_leave: 'Föräldraledig',
    training: 'Utbildning',
    other: 'Övrigt',
  },
} as const;

export const changeCmCopy = {
  title: 'Ändra Content Manager',
  description:
    'Permanent handover eller tillfällig coverage. Payroll delas pro rata per period.',
  now: 'Byt nu',
  nowDescription: 'Ny CM tar över från idag.',
  scheduled: 'Schemalägg',
  scheduledDescription: 'Bytet aktiveras på valt datum.',
  temporary: 'Tillfällig coverage',
  temporaryDescription: 'Täckning med start- och slutdatum.',
  startsOn: 'Startdatum',
  endsOn: 'Slutdatum',
  noCmAssigned: 'Ingen CM tilldelad',
  noEmail: 'Saknar e-post',
  commissionRate: (pct: number) => `${pct}% kommission`,
  compensationTitle: 'Provision under täckning',
  compensationBackup: 'Täckande CM får provision',
  compensationBackupDescription:
    'Ansvar och ersättning ligger på cover under perioden.',
  compensationPrimary: 'Ordinarie CM behåller provision',
  compensationPrimaryDescription:
    'Cover tar ansvar, men payout ligger kvar på ordinarie CM.',
  note: 'Intern notering',
  temporaryNotePlaceholder: 'Notering till coverage, frånvaro och payroll.',
  defaultNotePlaceholder: 'Valfri intern notering till audit och payroll.',
  previewTitle: (label: string) => `Pro rata-preview för perioden ${label}`,
  retainedCompensation:
    'Ordinarie CM behåller provision för cover-dagarna, men täckande CM tar operativt ansvar.',
  missingPrimary:
    'Kunden saknar ordinarie CM. Tillfällig coverage kan bara läggas på en befintlig ansvarig CM.',
  invalidCoverageRange: 'Slutdatum kan inte vara före startdatum.',
  selectReplacement: 'Välj en ersättare för att skapa coverage.',
  sameCmForTemporary: 'Ersättare måste vara en annan CM än ordinarie.',
  sameCmSelected: 'Nuvarande CM är redan vald.',
  alreadyUnassigned: 'Kunden har redan ingen ansvarig CM.',
  saveScheduled: 'Schemalägg byte',
  saveTemporary: 'Skapa coverage',
  saveNow: 'Byt CM',
  saving: 'Sparar...',
  cancel: 'Avbryt',
  current: 'Nuvarande CM',
  next: 'Ny CM',
  previewLoading: 'Hämtar preview...',
  previewFallback: 'Visar uppskattning lokalt eftersom server-preview inte kunde hämtas.',
  previewMissingPrice: 'Preview kan inte beräknas utan månadspris.',
  searchLabel: 'Sök CM',
  searchPlaceholder: 'Filtrera på namn eller e-post',
  noMatches: 'Ingen content manager matchar sökningen.',
  warningLabel: 'Observera',
} as const;
