import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

const supabase = createClient(supabaseUrl, supabaseKey)

const schemaFieldSchema = z.object({
  name: z.string(),
  type: z.enum(['number', 'string', 'boolean', 'select']),
  label: z.string(),
  description: z.string().optional(),
  required: z.boolean().default(false),
  min: z.number().optional(),
  max: z.number().optional(),
  step: z.number().optional(),
  options: z.array(z.string()).optional(),
  defaultValue: z.union([z.number(), z.string(), z.boolean()]).optional()
})

const evolveRequestSchema = z.object({
  fields: z.array(schemaFieldSchema),
  version: z.string().optional(),
  description: z.string(),
  autoGenerated: z.boolean().default(false)
})

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { fields, version, description, autoGenerated } = evolveRequestSchema.parse(body)

    console.log(`📋 Evolving rating schema (${fields.length} fields)`)

    // Get current active schema
    const { data: currentSchema } = await supabase
      .from('rating_schema_versions')
      .select('*')
      .eq('is_active', true)
      .single()

    // Generate version number
    const newVersion = version || `v${Date.now()}`

    // Deactivate current schema
    if (currentSchema) {
      await supabase
        .from('rating_schema_versions')
        .update({ is_active: false })
        .eq('id', currentSchema.id)
    }

    // Create new schema version
    const { data: newSchema, error: createError } = await supabase
      .from('rating_schema_versions')
      .insert({
        version: newVersion,
        schema: {
          fields,
          version: newVersion,
          description
        },
        description,
        is_active: true,
        auto_generated: autoGenerated,
        created_at: new Date().toISOString()
      })
      .select()
      .single()

    if (createError) {
      throw new Error(`Failed to create schema version: ${createError.message}`)
    }

    console.log(`✅ Schema evolved to ${newVersion}`)

    return NextResponse.json({
      version: newVersion,
      fields,
      description,
      previousVersion: currentSchema?.version || null,
      message: 'Rating schema evolved successfully'
    })

  } catch (error) {
    console.error('❌ Schema evolution failed:', error)
    
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { error: 'validation-error', details: error.errors },
        { status: 400 }
      )
    }

    return NextResponse.json(
      { 
        error: 'evolution-failed',
        message: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    )
  }
}

// GET - Get current active schema
export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams
    const version = searchParams.get('version')
    const includeHistory = searchParams.get('includeHistory') === 'true'

    if (includeHistory) {
      // Return all schema versions
      const { data: schemas, error } = await supabase
        .from('rating_schema_versions')
        .select('*')
        .order('created_at', { ascending: false })

      if (error) {
        throw new Error(`Failed to fetch schema history: ${error.message}`)
      }

      return NextResponse.json({
        schemas: schemas || [],
        count: schemas?.length || 0
      })
    }

    // Get specific version or active schema
    let query = supabase
      .from('rating_schema_versions')
      .select('*')

    if (version) {
      query = query.eq('version', version)
    } else {
      query = query.eq('is_active', true)
    }

    const { data: schema, error } = await query.single()

    if (error || !schema) {
      // Return default schema if none exists
      return NextResponse.json({
        version: 'default',
        fields: [
          {
            name: 'overall_rating',
            type: 'number',
            label: 'Overall Rating',
            description: 'Rate this video from 1-10',
            required: true,
            min: 1,
            max: 10,
            step: 0.5
          },
          {
            name: 'would_replicate',
            type: 'boolean',
            label: 'Would Replicate?',
            description: 'Would you want to make content like this?',
            required: false
          }
        ],
        description: 'Default rating schema',
        isDefault: true
      })
    }

    return NextResponse.json({
      version: schema.version,
      fields: schema.schema.fields,
      description: schema.description,
      createdAt: schema.created_at,
      autoGenerated: schema.auto_generated,
      isActive: schema.is_active
    })

  } catch (error) {
    console.error('❌ Fetch schema failed:', error)
    return NextResponse.json(
      { error: 'fetch-failed', message: 'Failed to retrieve schema' },
      { status: 500 }
    )
  }
}

// PATCH - Activate a specific schema version
export async function PATCH(request: NextRequest) {
  try {
    const body = await request.json()
    const { version } = z.object({
      version: z.string()
    }).parse(body)

    console.log(`🔄 Activating schema version: ${version}`)

    // Deactivate all schemas
    await supabase
      .from('rating_schema_versions')
      .update({ is_active: false })
      .eq('is_active', true)

    // Activate specified version
    const { error } = await supabase
      .from('rating_schema_versions')
      .update({ is_active: true })
      .eq('version', version)

    if (error) {
      throw new Error(`Failed to activate schema: ${error.message}`)
    }

    console.log(`✅ Schema ${version} activated`)

    return NextResponse.json({
      version,
      message: 'Schema version activated'
    })

  } catch (error) {
    console.error('❌ Schema activation failed:', error)
    
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { error: 'validation-error', details: error.errors },
        { status: 400 }
      )
    }

    return NextResponse.json(
      { error: 'activation-failed', message: 'Failed to activate schema' },
      { status: 500 }
    )
  }
}
