export const demosCopy = {
  pageTitle: 'Demos',
  pageSubtitle: 'Generera demo-l\u00e4nkar och f\u00f6lj upp leads.',
  loadingBoard: 'Laddar demos...',
  loadBoardError: 'Kunde inte ladda demos.',
  createButton: 'Ny demo',
  createSuccess: 'Ny demo skapades.',
  editSuccess: 'Demo uppdaterades.',
  emptyColumn: 'Inga demos h\u00e4r.',
  statusMoved: (companyName: string, nextLabelLower: string) =>
    `${companyName} flyttades till ${nextLabelLower}.`,
  statusLost: (companyName: string) => `${companyName} markerades som f\u00f6rlorad.`,
  convertedInvite: 'Demo konverterades och inbjudan skickades.',
  convertedCustomer: 'Demo konverterades till kund.',
  draftColumn: 'F\u00f6rberedd',
  sentColumn: 'Skickat',
  openedColumn: 'I dialog',
  respondedColumn: 'I dialog',
  quotedColumn: 'Offert',
  closedColumn: 'Avslutat',
  summarySent30: 'Skickade 30 dagar',
  summaryConverted30: 'Konverterade 30 dagar',
  summaryTotal: 'Totalt i boarden',
  copyLink: 'Kopiera demo-l\u00e4nk',
  copyLinkSuccess: 'Demo-l\u00e4nk kopierad.',
  copyLinkMissing: 'L\u00e4nk saknas \u2014 ladda om sidan.',
  openStudio: '\u00d6ppna i Studio',
  feedplanMissing: 'Feedplan ej f\u00f6rberedd',
  staleWarning: '\u00c4ldre \u00e4n 21 dagar \u2014 risk f\u00f6r d\u00f6d data',
  createDescription:
    'Fyll i grundinfo. Game Plan och AI-underlag l\u00e4gger du till i n\u00e4sta steg.',
  createCompanyPlaceholder: 'Caf\u00e9 Ros\u00e9',
  createPriceMonthlySek: 'Pris per m\u00e5nad (SEK)',
  ownerLabel: 'Content manager',
  ownerPlaceholder: 'V\u00e4lj CM',
  ownerMissing: 'Ingen CM',
  previewNotesLabel: 'Preview-noteringar',
  previewNotesPlaceholder: 'Kort intern notering om prospektets vinkel, nisch eller deal-context.',
  gamePlanLabel: 'Game Plan-utdrag',
  gamePlanPlaceholder:
    'Skriv en kort game plan som visas i previewn, eller generera ett utkast fr\u00e5n fr\u00e5gorna nedan.',
  gamePlanHelp: 'Visas i kundens demo-l\u00e4nk och kopieras till Studio vid f\u00f6rberedelse.',
  gamePlanAiButton: 'Generera utkast',
  gamePlanAiGenerating: 'Genererar...',
  gamePlanAiSuccess: 'Game Plan-utkast genererat. Granska texten innan du skickar l\u00e4nken.',
  strategyViewLabel: 'Nuvarande strategi',
  strategyViewPlaceholder: 'Vad tycker du om verksamhetens nuvarande TikTok- eller marknadsstrategi?',
  opportunitiesLabel: 'M\u00f6jligheter',
  opportunitiesPlaceholder: 'Vilka format, hooks eller beteenden ser du att LeTrend kan bygga vidare p\u00e5?',
  letrendFitLabel: 'Varf\u00f6r LeTrend',
  letrendFitPlaceholder: 'Varf\u00f6r kan just den h\u00e4r verksamheten dra nytta av feed planner, CM och kuraterade koncept?',
  studioConceptCountLabel: (count: number) => `${count} studio-koncept`,
  createInfo:
    'E-post och pris kan fyllas i senare. Konvertering till kund blir tydligare om de finns redan nu.',
  convertDescription:
    'Skapa kundprofil direkt fr\u00e5n demo och skicka inbjudan om e-post finns.',
  convertNoContactEmail: 'Ingen kontaktmail satt',
  convertMissingPrice: 'Pris saknas',
  convertPriceLabel: (price: string) => `Prisf\u00f6rslag: ${price}`,
  convertInviteDescription:
    'Kunden f\u00e5r invite-fl\u00f6det direkt efter konvertering.',
  convertInviteMissingEmail:
    'Kan inte skicka inbjudan utan kontaktmail p\u00e5 demon.',
  statusNoFurtherAction: 'Ingen vidare action fr\u00e5n boarden',
  statusConverted: 'Konverterad',
  noTikTokHandle: 'Ingen TikTok-handle',
  noTempo: 'Tempo ej satt',
  noPrice: 'Pris ej satt',
  noContactEmail: 'Ingen kontaktmail',
  updatedPrefix: 'Uppdaterad',
  lostReasonPrefix: 'Orsak:',
  saveInProgress: 'Sparar...',
  convertButton: 'Konvertera till kund',
  loseButton: 'Markera f\u00f6rlorad',
  convertDialogTitle: 'Konvertera demo',
  editDialogTitle: 'Redigera demo',
  editDescription: 'Uppdatera prospektdata, TikTok-handle, pris och ansvarig CM.',
  editDialogSubmit: 'Spara demo',
  createDialogTitle: 'Ny demo',
  createDialogSubmit: 'Skapa demo',
  createDialogSubmitting: 'Skapar...',
  createDialogSubmittingWithSync: 'Skapar och h\u00e4mtar historik...',
  convertDialogSubmit: 'Konvertera till kund',
  convertDialogSubmitting: 'Konverterar...',
  inviteDirectLabel: 'Skicka inbjudan direkt',
  startDateLabel: 'Startdatum',
  billingDayLabel: 'Fakturadag',
  companyLabelRequired: 'Bolag *',
  contactLabel: 'Kontaktperson',
  emailLabel: 'E-post',
  tiktokLabel: 'TikTok-handle',
  conceptsPerWeekLabel: 'Koncept per vecka',
  markConverted: 'Konverterad',
  gamePlanDrawerTitle: 'Game Plan',
  gamePlanDrawerDescription:
    'Skriv eller AI-generera ett Game Plan-utkast. Du kan hoppa \u00f6ver detta och \u00e5terkomma senare.',
  gamePlanDrawerSave: 'Spara Game Plan',
  gamePlanDrawerSkip: 'Hoppa \u00f6ver',
  gamePlanDrawerActionLabel: 'Game Plan',
  gamePlanNextStepHint:
    'Game Plan och preview-noteringar fylls i i n\u00e4sta steg direkt efter att demot skapats.',
} as const;
