export const overviewCopy = {
  invalidQueryParams: 'Ogiltiga query-parametrar',
  loadOverviewError: 'Kunde inte h\u00e4mta \u00f6versikt',
  loadCustomersError: 'Kunde inte h\u00e4mta kunder',
  loadTeamError: 'Kunde inte h\u00e4mta team',
  loadInteractionsError: 'Kunde inte h\u00e4mta interaktioner',
  loadBufferError: 'Kunde inte h\u00e4mta bufferdata',
  loadNotificationsError: 'Kunde inte h\u00e4mta CM-notiser',
  loadSnoozesError: 'Kunde inte h\u00e4mta hanteras-markeringar',
  loadInvoicesError: 'Kunde inte h\u00e4mta f\u00f6rfallna fakturor',
  loadSubscriptionsError: 'Kunde inte h\u00e4mta abonnemang',
  loadCostsError: 'Kunde inte h\u00e4mta kostnader',
  loadDemosError: 'Kunde inte h\u00e4mta demos',
  unknownCustomer: 'Ok\u00e4nd kund',
  unknownName: 'Ok\u00e4nd',
} as const;
