export const SHELL_COPY = {
  overview: '\u00d6versikt',
  customers: 'Kunder',
  billing: 'Billing',
  team: 'Team',
  demos: 'Demos',
  notifications: 'Notifikationer',
  ops: 'Ops',
  logout: 'Logga ut',
  adminBadge: 'Admin',
  unreadAria: (count: number) => `${count} ol\u00e4sta notifikationer`,
  openNotifications: '\u00d6ppna notifikationer',
  working: 'Arbetar...',
  loadingShell: 'Laddar admin...',
  openMenu: '\u00d6ppna meny',
  closeMenu: 'St\u00e4ng meny',
  collapseMenu: 'Minimera meny',
  expandMenu: 'Expandera meny',
  skipToContent: 'Hoppa till inneh\u00e5ll',
  adminNavigationAria: 'Admin-navigering',
  defaultEyebrow: 'LeTrend Admin',
} as const;
